### PR TITLE
added player table

### PR DESCRIPTION
**Pull request by kaubster**
Added PlayerTable component to game table

Arranges players by name in turn order counter clockwise along the circumference of a circle.

Your name turns green (with "Go" icon) when its your turn
Other player taking a turn is orange (no icon)
All other players and you (when not your turn) are black (no icon)

Fixed DiceBoard.test.js which were failing after merge.

### CODE REVIEW

**Comment by cvennel** [comment]
image

**Comment by cvennel** [comment]
image

Is this rendering correctly?

**Comment by kaubster** [comment]
Fixed rendering issues... hopefully. Give it a whirl..

did test in firefox though we have redirect issues which are not related to this defect.

**Comment by cvennel** [comment]
image

**Comment by cvennel** [comment]
cool!

**Pull request merged**
