### PR TITLE
final commit :)

### PR DESCRIPTION
**Pull request by otaiwo70**
final commit 

Documentation added
Test cases for model

### CODE REVIEW

**Comment by cvennel** [comment]
Sorry to be nitpicky, but the Developers section in the word doc has current developers from this quarter. We should give credit where credit is due and include all developers. https://github.com/borisv13/kot/graphs/contributors

**Comment by kaubster** [comment]
Bit confused by the committers listing. Apparently I should have pushed my own merge buttons. LOL.

**Comment by otaiwo70** [comment]
That is very true, they do deserve credit, let me make that correction

**Comment by otaiwo70** [comment]
added the folks from last quarter

**Pull request merged**
